name: fineganfinch
favicon: null
layout_spectrum: 0.6226737489923835
typography_spectrum: 0.13802
title: FINEGAN FINCH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a100e'
    - '#39dea2'
    - '#ebfdef'
    - '#a7e697'
    - '#217758'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
